[*]
desktop_bg=#000000
desktop_shadow=#000000
desktop_fg=#3EEE12
desktop_font=DejaVu Sans Bold Semi-Condensed 12
wallpaper=/usr/share/rpd-wallpaper/sunrise.jpg
wallpaper_mode=crop
show_home=1
show_trash=1
show_mounts=1
folder=/home/dynogator/Desktop
