#!/data/data/com.termux/files/usr/bin/bash
# dslv-zpdi Mobile Tier-2 Automated Deployment Script
# Execute natively in Termux to transform an Android device into a production node.

set -euo pipefail

LOG_FILE="$HOME/install_zpdi.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "======================================================="
echo "   dslv-zpdi Mobile Node Automated Installer (Rev 4)   "
echo "======================================================="
echo "[*] Starting deployment at $(date)"

# 1. System Preparation
echo "[*] Enforcing Termux Storage Setup..."
termux-setup-storage || true
sleep 2

echo "[*] Requesting Android Wake-Lock..."
termux-wake-lock || echo "[!] WARNING: termux-wake-lock failed. Install Termux:API."

# 2. Dependency Management
echo "[*] Updating Termux pkg repositories..."
pkg update -y

echo "[*] Installing Termux dependencies (proot-distro, termux-api, git, openssl)..."
pkg install -y proot-distro termux-api git openssl

# 3. PRoot Debian Configuration
echo "[*] Installing/Verifying Debian PRoot..."
proot-distro install debian || echo "[*] Debian already installed."

# 4. Constructing PRoot execution bridge
BOOTSTRAP_SCRIPT="$HOME/bootstrap_proot.sh"
cat << 'EOF' > "$BOOTSTRAP_SCRIPT"
#!/bin/bash
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "[*] [Debian] Updating apt repositories..."
apt-get update -y
echo "[*] [Debian] Installing build dependencies..."
apt-get install -y python3 python3-venv python3-dev git build-essential libhdf5-dev pkg-config cmake sqlite3 curl openssl

if [ ! -d "/root/dslv-zpdi" ]; then
    echo "[*] [Debian] Cloning repository..."
    # Replace with the actual repository URL once deployed
    git clone https://github.com/placeholder/dslv-zpdi.git /root/dslv-zpdi
else
    echo "[*] [Debian] Repository exists. Pulling latest..."
    cd /root/dslv-zpdi
    git fetch && git pull
fi

cd /root/dslv-zpdi

echo "[*] [Debian] Setting up Python virtual environment..."
python3 -m venv .venv
source .venv/bin/activate

echo "[*] [Debian] Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo "[*] [Debian] Generating secure .env..."
if [ ! -f ".env" ]; then
    AES_KEY=$(openssl rand -base64 32)
    HMAC_SECRET=$(openssl rand -hex 32)
    cat <<ENV_EOF > .env
ZPDI_LOG_LEVEL=INFO
ZPDI_STREAM_DELAY_MS=250
ZPDI_NODE_ID=dslv-zpdi/mobile-tier2-autodeploy
ZPDI_AES_KEY=${AES_KEY}
ZPDI_HMAC_SECRET=${HMAC_SECRET}
ZPDI_WSS_URI=wss://edge.placeholder.invalid:8443/ingest
ENV_EOF
    echo "[*] [Debian] .env generated securely."
else
    echo "[*] [Debian] .env already exists. Preserving."
fi
EOF

chmod +x "$BOOTSTRAP_SCRIPT"

echo "[*] Bridging into Debian PRoot..."
proot-distro login debian -- bash "$BOOTSTRAP_SCRIPT"

# 5. Configuration & Termux:Boot Hooks
echo "[*] Securing Termux:Boot persistence layer..."
mkdir -p "$HOME/.termux/boot"

# We must ensure the boot script exists in the repository, but since the
# repository is in PRoot (/root/dslv-zpdi), we can't easily symlink across PRoot
# boundaries safely for Termux:Boot. Instead, we extract the daemon launcher directly
# into the Termux boot folder.

cat << 'BOOT_EOF' > "$HOME/.termux/boot/99-start-zpdi.sh"
#!/data/data/com.termux/files/usr/bin/bash
# dslv-zpdi Termux:Boot auto-start script (Autogenerated)
set -euo pipefail

BOOT_LOG="$HOME/.termux/boot/zpdi-boot.log"
PROOT_DISTRO="/data/data/com.termux/files/usr/bin/proot-distro"
PROJECT_DIR="/root/dslv-zpdi"
SUPERVISOR="$PROJECT_DIR/supervisor.sh"

echo "$(date '+%Y-%m-%d %H:%M:%S') [zpdi-boot] Boot event received" >> "$BOOT_LOG"

if command -v termux-wake-lock >/dev/null 2>&1; then
    termux-wake-lock
    echo "$(date '+%Y-%m-%d %H:%M:%S') [zpdi-boot] wake-lock acquired" >> "$BOOT_LOG"
fi

pkill -SIGTERM -f "supervisor.sh" 2>/dev/null || true
pkill -SIGTERM -f "zpdi_mobile_node.py" 2>/dev/null || true
sleep 1
pkill -SIGKILL -f "zpdi_mobile_node.py" 2>/dev/null || true

# Clear stale HDF5 lock in PRoot
$PROOT_DISTRO login debian -- h5clear -s "$PROJECT_DIR/data/zpdi_stream.h5" 2>/dev/null || true

nohup "$PROOT_DISTRO" login debian -- bash "$SUPERVISOR" >> "$BOOT_LOG" 2>&1 &
echo "$(date '+%Y-%m-%d %H:%M:%S') [zpdi-boot] supervisor launched (proot PID=$!)" >> "$BOOT_LOG"
BOOT_EOF

chmod +x "$HOME/.termux/boot/99-start-zpdi.sh"

echo "[*] Cleaning up temporary artifacts..."
rm -f "$BOOTSTRAP_SCRIPT"

# 6. Verification
echo "======================================================="
echo "   [SUCCESS] dslv-zpdi Mobile Node Deployed   "
echo "======================================================="
echo ""
echo "  Persistence configured via ~/.termux/boot/99-start-zpdi.sh"
echo "  Secure crypto payloads configured in PRoot ~/.env"
echo ""
echo "  ACTION REQUIRED: Reboot Android device to validate"
echo "  Termux:Boot daemon recovery."
echo "======================================================="
