"""Dark-humor scan messages rotator — DynoGatorLabs."""

import random
import time

SCAN_MESSAGES = [
    "SCANNING FOR PLASMOIDS",
    "AUSCULTATING THE IONOSPHERE",
    "INTERROGATING THE AETHER",
    "TRIANGULATING NON-CONSENSUS REALITIES",
    "LISTENING FOR CETACEAN WHISPERS AT 1420 MHz",
    "CROSS-CORRELATING DREAM FRAGMENTS",
    "QUARANTINING ROGUE PHOTONS",
    "CHECKING CLOSET FOR GPSDO-SHAPED HOLES",
    "COUNTING ADC BITS BACKWARDS",
    "UNFOLDING THE KURAMOTO MANIFOLD",
    "ENTICING ANOMALOUS CARRIERS",
    "NEGOTIATING WITH THE UPS CAPACITORS",
    "FLIRTING WITH 50-OHM IMPEDANCE",
    "INVOKING SCHOTTKY BARRIER PRIESTS",
    "ASKING THE HACKRF POLITELY",
    "SHOUTING AT THE 1 PPS LINE",
    "OFFERING COFFEE TO THE RP1 SOUTHBRIDGE",
    "BRIBING CHRONY WITH SUB-MICROSECOND NONSENSE",
    "BACKSCATTER-TRANSMUTING COSMIC RAYS",
    "APOLOGIZING TO THE 10 MHz REFERENCE",
    "BAYESIAN-FLAVORED OUTLIER HUNTING",
    "SPELUNKING THE RF SPECTRUM",
    "RECALIBRATING THE GRAVITAS SENSOR",
    "CONVINCING NYQUIST TO LET US PASS",
    "DECODING WHAT THE ANTENNA REFUSES TO SAY",
    "PROBING THE DIELECTRIC SOUL",
    "MISTRUSTING THE USB STACK (AGAIN)",
    "CHATTING WITH VAN ALLEN'S GHOST",
    "HOT-SWAPPING QUANTUM EIGENSTATES",
    "BUFFERING BEYOND ALL REASON",
    "PROFESSIONALLY LOITERING IN THE L-BAND",
    "SYMPATHETICALLY OSCILLATING WITH CESIUM",
    "MILDLY HARASSING NEUTRINOS",
    "DIAGONALIZING THE COHERENCE TENSOR",
    "DETECTING DARK HUMOR AT -110 dBm",
    "REMINDING ENTROPY WHO'S IN CHARGE",
    "RATIONALIZING THE IRRATIONAL (FLOATING-POINT)",
    "TIMESTAMP JITTER IS JUST EMOTIONAL RANGE",
    "LET HIM COOK (THE HackRF)",
    "DOWNSAMPLING YOUR EXPECTATIONS",
]

GLITCH_MESSAGES = [
    "!!! ANOMALY AT 137.5 MHz !!! (just a weather sat)",
    "PLASMOID CONFIRMED (confidence: 0.4%)",
    "REALITY CHECK PASSED (barely)",
    "KCET-ATLAS AGREES WITH ITSELF",
    "PHASE LOCK SOMEHOW MAINTAINED",
    "THE GHOST IN THE SHELL IS JUST ADC ALIASING",
    "COHERENCE SCORE: YES",
    "TELEMETRY CONFIDENT, USERBASE UNCERTAIN",
]


def pick_scan() -> str:
    """Deterministic pick keyed to current 3-second window."""
    seed = int(time.time()) // 3
    rng = random.Random(seed)
    return rng.choice(SCAN_MESSAGES)


def pick_glitch() -> str:
    """Rare-event flavor line."""
    return random.choice(GLITCH_MESSAGES)
