/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as BookRouteImport } from './routes/book'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as WalkRouteImport } from './routes/walk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/book': typeof BookRoute
  '/doctrine': typeof DoctrineRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/book': typeof BookRoute
  '/doctrine': typeof DoctrineRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/book': typeof BookRoute
  '/doctrine': typeof DoctrineRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bench' | '/book' | '/doctrine' | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bench' | '/book' | '/doctrine' | '/walk'
  id: '__root__' | '/' | '/bench' | '/book' | '/doctrine' | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRoute: typeof BenchRoute
  BookRoute: typeof BookRoute
  DoctrineRoute: typeof DoctrineRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRoute: BenchRoute,
  BookRoute: BookRoute,
  DoctrineRoute: DoctrineRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
