# This contains only GUI settings for GRC and is not meant for users to edit.
#
# GRC settings not accessible through the GUI are in config.conf under
# section [grc].

[main]
file_open = 
main_window_width = 1024
main_window_height = 538
console_window_position = 374
blocks_window_position = 877
variable_editor_position = 261

[files_recent]

[files_open]

