[greeter]
default-user-image=/usr/share/raspberrypi-artwork/raspberry-pi-logo.png
desktop_bg=#d6d6d3d3dede
wallpaper=/usr/share/rpd-wallpaper/RPiSystem_dark.png
wallpaper_mode=crop
gtk-theme-name=PiXonyx
gtk-icon-theme-name=PiXtrix
gtk-font-name=DejaVu Sans Bold Semi-Condensed 12
