#!/usr/bin/env bash
# Toggle the DSLV-ZPDI pipeline between simulated HAL and hardware HAL.
#
# Writes or removes a systemd drop-in at:
#   /etc/systemd/system/dslv-zpdi.service.d/99-simulator.conf
#
# Usage:
#   sudo tools/toggle_simulator.sh on          # force simulator mode
#   sudo tools/toggle_simulator.sh off         # force hardware mode
#   sudo tools/toggle_simulator.sh status      # show current mode (no sudo required)
#   sudo tools/toggle_simulator.sh demo on     # simulator + DSLV_SIM_DEMO=1 (event generator)
#   sudo tools/toggle_simulator.sh demo off    # simulator without demo event generator

set -Eeuo pipefail

DROPIN_DIR="/etc/systemd/system/dslv-zpdi.service.d"
DROPIN_FILE="$DROPIN_DIR/99-simulator.conf"
VENV_PY="/home/dynogator/dslv-zpdi/venv/bin/python"
UNIT="dslv-zpdi.service"

usage() {
  sed -n '2,12p' "$0"
  exit 1
}

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "error: must run with sudo (writes to $DROPIN_DIR and restarts $UNIT)" >&2
    exit 1
  fi
}

reload_restart() {
  systemctl daemon-reload
  systemctl restart "$UNIT"
  echo "Restarted $UNIT."
}

current_mode() {
  # Prefer drop-in if present
  if [ -f "$DROPIN_FILE" ]; then
    if grep -q -- '--hardware' "$DROPIN_FILE"; then
      echo "hardware"
      return
    fi
    if grep -q 'DSLV_SIM_DEMO=1' "$DROPIN_FILE"; then
      echo "simulator+demo"
      return
    fi
    echo "simulator (drop-in)"
    return
  fi
  # Fall back to the baked-in service file (which currently defaults to --simulator)
  if systemctl cat "$UNIT" 2>/dev/null | grep -q -- '--hardware'; then
    echo "hardware"
  else
    echo "simulator (default)"
  fi
}

write_dropin_hardware() {
  mkdir -p "$DROPIN_DIR"
  cat > "$DROPIN_FILE" <<EOF
# Generated by tools/toggle_simulator.sh — forces hardware HAL.
[Service]
Environment=DSLV_SIMULATOR=0
Environment=DEV_SIMULATOR=0
Environment=DSLV_SIM_DEMO=0
ExecStart=
ExecStart=$VENV_PY -m dslv_zpdi.main_pipeline --hardware
EOF
}

write_dropin_simulator() {
  local demo="${1:-0}"
  mkdir -p "$DROPIN_DIR"
  cat > "$DROPIN_FILE" <<EOF
# Generated by tools/toggle_simulator.sh — forces simulator HAL.
[Service]
Environment=DSLV_SIMULATOR=1
Environment=DEV_SIMULATOR=1
Environment=DSLV_SIM_DEMO=${demo}
ExecStart=
ExecStart=$VENV_PY -m dslv_zpdi.main_pipeline --simulator
EOF
}

cmd="${1:-status}"
sub="${2:-}"

case "$cmd" in
  status)
    echo "mode: $(current_mode)"
    if [ -f "$DROPIN_FILE" ]; then
      echo "drop-in: $DROPIN_FILE"
      sed 's/^/  /' "$DROPIN_FILE"
    else
      echo "drop-in: (none)"
    fi
    ;;
  on)
    need_root
    write_dropin_simulator 0
    echo "Wrote $DROPIN_FILE (simulator)."
    reload_restart
    ;;
  off)
    need_root
    write_dropin_hardware
    echo "Wrote $DROPIN_FILE (hardware)."
    reload_restart
    ;;
  demo)
    need_root
    case "$sub" in
      on)  write_dropin_simulator 1; echo "Wrote $DROPIN_FILE (simulator + demo events).";;
      off) write_dropin_simulator 0; echo "Wrote $DROPIN_FILE (simulator, demo off).";;
      *)   echo "error: demo requires 'on' or 'off'" >&2; exit 1;;
    esac
    reload_restart
    ;;
  clear)
    need_root
    rm -f "$DROPIN_FILE"
    echo "Removed $DROPIN_FILE (reverted to service-file default)."
    reload_restart
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    echo "error: unknown command '$cmd'" >&2
    usage
    ;;
esac
